apiVersion: config.openshift.io/v1
kind: Authentication
metadata:
  name: cluster
spec:
  oauthMetadata:
    name: ""
  serviceAccountIssuer: ""
  type: ""
  oidcProviders:
  webhookTokenAuthenticator:
    kubeConfig:
      name: webhook-authentication-integrated-oauth
