apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-new-worker-example-myname
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,cHJhbW9kcmVkaGF0Cg==
        filesystem: root
        mode: 0644
        path: /etc/myname.conf
